# This is a basic workflow to help you get started with Actions

name: ParselTongue

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    ParselTongue:
    # The type of runner that the job will run on
        runs-on: windows-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
          name: Checkout Code
          
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
              dotnet-version: 3.1.x

        - name: Install Dependencies
          run: dotnet restore Parsiey/Parsiey.sln
          
        - name: Build
          run: dotnet build Parsiey/Parsiey.sln --configuration Release --no-restore

        - name: Upload Artifact
          uses: actions/upload-artifact@v2.1.4
          with: 
            name: Parsiey.exe
            path: Parsiey/Parsiey/obj/Debug/netcoreapp3.1/
